services:
  #DB
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - red_laravel

  #Laravel
  backend:
    build: ./practicaLaravel
    container_name: laravel-app
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./practicaLaravel:/var/www
    command: >
      sh -c "composer install &&
             php artisan migrate --force &&
             php artisan db:seed --force &&
             php artisan serve --host=0.0.0.0 --port=9000"
    networks:
      - red_laravel
  #Front
  frontend:
    build: ./frontend
    container_name: php-web
    restart: always
    depends_on:
      - backend
    volumes:
      - ./frontend/index.php:/var/www/html/index.php
    ports:
      - "8080:80"
    command: 
      ["apache2-foreground"]
    networks:
      - red_laravel

volumes:
  mysql_data:

networks:
  red_laravel:
    driver: bridge
